### PR TITLE
fix(README.MD): update the latest stable version

### PR DESCRIPTION
**Pull request by AliMD**
the latest stable version is v1.0.0-beta.14

### CODE REVIEW

**Comment by drastick** [comment]
+1

**Comment by toddhalfpenny** [comment]
Need to update the PR to reflect RC-0 now.

**Comment by zfoltin** [comment]
At this point the latest seems to be 1.2.4, yet there were a few changes since then
https://github.com/driftyco/ionic-bower/compare/v1.2.4...master
I use driftyco/ionic-bower#master to get the latest and greatest

**Comment by AliMD** [comment]
#28
Could you please check your PR's

**Pull request closed without merging**
